apiVersion: 1

datasources:

  - name:      Prometheus
    type:      prometheus
    uid:       prometheus
    url:       http://prometheus:9090
    isDefault: true
    access:    proxy
    jsonData:
      httpMethod:       POST
      timeInterval:     10s

  - name:   Loki
    type:   loki
    uid:    loki
    url:    http://loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex:  "cluster_id=([a-z0-9-]+)"
          name:          ClusterID
          url:           '/explore?orgId=1&left={"datasource":"prometheus","queries":[{"expr":"quorum_cluster_health{id=\"${__value.raw}\"}"}]}'
